name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: Clippy
      uses: auguwu/clippy-action@1.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        check-args: --all-features --all-targets
        

    - name: Rustfmt Check
      uses: actions-rust-lang/rustfmt@v1

    - name: Run tests
      run: cargo test --verbose

    - name: Run tests (miri)
      run: |
        rustup toolchain add nightly
        rustup +nightly component add miri
        cargo +nightly miri test
